export const PortfolioData = [
  {
    id: 1,
    type: "web",
    featured: true,
    title: "Photocelos",
    img: "/portfolio/web/photocelos.jpg",
    desc: "This project aims to showcase the heritage of the municipality of Barcelos",
    link: "",
  },
  {
    id: 2,
    type: "web",
    featured: false,
    title: "Alotecnica",
    img: "/portfolio/web/alotecnica.jpeg",
    desc: "A elegant and simple website for a mobile phone repair company in Barcelos",
    link: "",
  },
  {
    id: 3,
    type: "web",
    featured: false,
    title: "Belofer",
    img: "/portfolio/web/belofer.png",
    desc: "Belofer consulted us for the creation of their website. A simple but elegant website.",
    link: "",
  },
  {
    id: 4,
    type: "web",
    featured: false,
    title: "Credivida",
    img: "/portfolio/web/credivida.png",
    desc: "A elegant and simple website for a credit company",
    link: "",
  },
  {
    id: 5,
    type: "web",
    featured: true,
    title: "Motocavaquinhos",
    img: "/portfolio/web/motocavaquinho.png",
    desc: "A elegant and simple website for a motorcycle association in Barcelos",
    link: "",
  },
  {
    id: 7,
    type: "web",
    featured: false,
    title: "Tecniwall",
    img: "/portfolio/web/tecniwall.jpg",
    desc: "A elegant and simple website for a construction company in Barcelos",
    link: "http://www.tecniwall.com/",
  },
  {
    id: 8,
    type: "web",
    featured: false,
    title: "Vouga Plazza",
    img: "/portfolio/web/vouga-plazza.png",
    desc: "A simple and elegant website for a restaurant in Barcelos",
    link: "",
  },
  {
    id: 9,
    type: "web",
    featured: false,
    title: "Ritual Restaurante",
    img: "/portfolio/web/ritual-restaurante.png",
    desc: "A simple and elegant website for a restaurant in Barcelos",
    link: "",
  },
  {
    id: 10,
    type: "web",
    featured: false,
    title: "Paula Soares da Costa",
    img: "/portfolio/web/paulasoarescosta.png",
    desc: "A simple and elegant website for an accounting firm",
    link: "",
  },
  {
    id: 11,
    type: "web",
    featured: false,
    title: "Clinica de Medicina de Famalicão",
    img: "/portfolio/web/clinicamedicinafamalicao.png",
    desc: "A simple and elegant website for a medical clinic in Famalicão",
    link: "",
  },
  {
    id: 12,
    type: "web",
    featured: false,
    title: "IncentivoPT",
    img: "/portfolio/web/incentivopt.png",
    desc: "A simple and elegant website for a tax incentive company",
    link: "",
  },
  {
    id: 13,
    type: "mobile",
    featured: false,
    title: "Viver Barcelos",
    img: "/portfolio/mobile/viverBarcelos.jpg",
    desc: "An application that aims to show the heritage of the municipality of Barcelos",
    link: "",
  },
  {
    id: 14,
    type: "mobile",
    featured: true,
    title: "TempoApp",
    img: "/portfolio/mobile/tempoApp.jpg",
    desc: "A mobile application created during the learning period of JavaScript",
    link: "https://github.com/Foskiitus/tempoApp",
  },
  {
    id: 15,
    type: "web",
    featured: true,
    title: "Evently",
    img: "/portfolio/web/evently.svg",
    desc: "A simple event management application in NextJS 14",
    link: "https://github.com/Foskiitus/evently",
  },
  {
    id: 16,
    type: "web",
    featured: true,
    title: "Tarefas+",
    img: "/portfolio/web/tarefas.png",
    desc: "A simple task management application in NextJS 14",
    link: "https://github.com/Foskiitus/ProjetoBoardTarefas/",
  },
];

export const worksData = [
  {
    id: 1,
    icon: "./assets/mobile.png",
    title: "Viver Barcelos",
    desc: "lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    img: "./assets/portfolio/mobile/viverBarcelos.jpg",
  },
  {
    id: 2,
    icon: "./assets/mobile.png",
    title: "TempoApp",
    desc: "É uma aplicação mobile criada durante o período de aprendizagem de JavaScript",
    img: "./assets/portfolio/mobile/tempoApp.jpg",
  },
  {
    id: 3,
    icon: "./assets/globe.png",
    title: "Belofer",
    desc: "Belofer é um website de uma empresa do ramo do comercio de peças para a industria têxtil de Barcelos",
    img: "assets/portfolio/web/belofer.png",
  },
];

export const testemonialsData = [
  {
    id: 1,
    name: "Jorge",
    title: "DOTE INVESTE, LDA",
    img: "assets/avatar.png",
    icon: "assets/youtube.png",
    desc: "De salientar a rapidez e a intercomunicabilidade em todo processo de criação.",
    featured: false,
  },
  {
    id: 2,
    name: "PRESIDENTE",
    title: "MOTOCAVAQUINHOS",
    img: "assets/avatar.png",
    icon: "assets/youtube.png",
    desc: "Um site barato, rápido e agradável.",
    featured: true,
  },
];
