export const PortfolioData = [
  {
    id: 1,
    type: "web",
    featured: true,
    title: "Photocelos",
    img: "./src/assets/portfolio/web/photocelos.jpg",
    desc: "Este projecto tem por objectivo dar a conhecer o patrimonio do concelho de Barcelos",
    link: "",
  },
  {
    id: 2,
    type: "web",
    featured: false,
    title: "Alotecnica",
    img: "./src/assets/portfolio/web/alotecnica.jpeg",
    desc: "Um website simples e elegante para uma empresa de reparação de telemóveis em Barcelos",
    link: "",
  },
  {
    id: 3,
    type: "web",
    featured: false,
    title: "Belofer",
    img: "./src/assets/portfolio/web/belofer.png",
    desc: "A Belofer consultou-nos para a criação do seu web site. Um website simples mas elegante.",
    link: "",
  },
  {
    id: 4,
    type: "web",
    featured: false,
    title: "Credivida",
    img: "./src/assets/portfolio/web/credivida.png",
    desc: "Website simples e elegante para uma empresa de créditos",
    link: "",
  },
  {
    id: 5,
    type: "web",
    featured: true,
    title: "Motocavaquinhos",
    img: "./src/assets/portfolio/web/motocavaquinho.png",
    desc: "Um website simples para uma associação de motociclistas de Barcelos",
    link: "",
  },
  {
    id: 7,
    type: "web",
    featured: false,
    title: "Tecniwall",
    img: "./src/assets/portfolio/web/tecniwall.jpg",
    desc: "Um website simples e elegante para uma empresa de construção civil em Barcelos",
    link: "http://www.tecniwall.com/",
  },
  {
    id: 8,
    type: "web",
    featured: false,
    title: "Vouga Plazza",
    img: "./src/assets/portfolio/web/vouga-plazza.png",
    desc: "Um website simples e elegante para um restaurante em Barcelos",
    link: "",
  },
  {
    id: 9,
    type: "web",
    featured: false,
    title: "Ritual Restaurante",
    img: "./src/assets/portfolio/web/ritual-restaurante.png",
    desc: "Um website simples e elegante para um restaurante em Barcelos",
    link: "",
  },
  {
    id: 10,
    type: "web",
    featured: false,
    title: "Paula Soares da Costa",
    img: "./src/assets/portfolio/web/paulasoarescosta.png",
    desc: "Um website simples e elegante para uma empresa de contabilidade",
    link: "",
  },
  {
    id: 11,
    type: "web",
    featured: false,
    title: "Clinica de Medicina de Famalicão",
    img: "./src/assets/portfolio/web/clinicamedicinafamalicao.png",
    desc: "Um Website simples e elegante para uma clinica de medicina dentária em Famalicão",
    link: "",
  },
  {
    id: 12,
    type: "web",
    featured: false,
    title: "IncentivoPT",
    img: "./src/assets/portfolio/web/incentivopt.png",
    desc: "Um website simples e elegante para uma empresa de incentivos fiscais",
    link: "",
  },
  {
    id: 13,
    type: "mobile",
    featured: false,
    title: "Viver Barcelos",
    img: "./src/assets/portfolio/mobile/viverBarcelos.jpg",
    desc: "Uma aplicação mobile criada para a dar a conhecer Barcelos",
    link: "",
  },
  {
    id: 14,
    type: "mobile",
    featured: true,
    title: "TempoApp",
    img: "./src/assets/portfolio/mobile/tempoApp.jpg",
    desc: "Uma aplicação simples criada no decorrer de uma formação",
    link: "https://github.com/Foskiitus/tempoApp",
  },
  {
    id: 15,
    type: "web",
    featured: true,
    title: "Evently",
    img: "./src/assets/portfolio/web/evently.svg",
    desc: "Uma aplicação em NextJS 14 para gestão de eventos",
    link: "https://github.com/Foskiitus/evently",
  },
  {
    id: 16,
    type: "web",
    featured: true,
    title: "Tarefas+",
    img: "./src/assets/portfolio/web/tarefas.png",
    desc: "Uma aplicação de tarefas em NextJS 14",
    link: "https://github.com/Foskiitus/ProjetoBoardTarefas/",
  },
];

export const worksData = [
  {
    id: 1,
    icon: "./assets/mobile.png",
    title: "Viver Barcelos",
    desc: "lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    img: "./assets/portfolio/mobile/viverBarcelos.jpg",
  },
  {
    id: 2,
    icon: "./assets/mobile.png",
    title: "TempoApp",
    desc: "É uma aplicação mobile criada durante o período de aprendizagem de JavaScript",
    img: "./assets/portfolio/mobile/tempoApp.jpg",
  },
  {
    id: 3,
    icon: "./assets/globe.png",
    title: "Belofer",
    desc: "Belofer é um website de uma empresa do ramo do comercio de peças para a industria têxtil de Barcelos",
    img: "assets/portfolio/web/belofer.png",
  },
];

export const testemonialsData = [
  {
    id: 1,
    name: "Jorge",
    title: "DOTE INVESTE, LDA",
    img: "assets/avatar.png",
    icon: "assets/youtube.png",
    desc: "De salientar a rapidez e a intercomunicabilidade em todo processo de criação.",
    featured: false,
  },
  {
    id: 2,
    name: "PRESIDENTE",
    title: "MOTOCAVAQUINHOS",
    img: "assets/avatar.png",
    icon: "assets/youtube.png",
    desc: "Um site barato, rápido e agradável.",
    featured: true,
  },
];
